name: "Deploy-Functions"

on:
  workflow_call:
    inputs:
      environment:
        description: "Name of the environment to deploy to"
        required: true
        type: string
permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{inputs.environment}}
      url: https://${{inputs.environment}}-attachmentfunctions.azurewebsites.net
    env:
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID }}
      TENANT_ID: ${{secrets.TENANT_ID}}

    steps:
        - run: echo "DEPLOYING THE API..."