name: "Deploy-Environment"

on:
  workflow_call:
    inputs: 
      use_approval_gate:
        description: "Use an approval before running deployment steps"
        required: false
        default: true
        type: boolean
      environment:
        description: "Name of the environment to deploy to"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  checks: write

defaults:
  run:
    shell: pwsh

jobs:
  
  approval-gate:
    if: ${{ inputs.use_approval_gate }}
    runs-on: ubuntu-latest
    environment: "${{ inputs.environment }}-approval"
    concurrency:
      cancel-in-progress: true
      group: ${{ inputs.environment }}-approval
    steps:
      - name: approved
        env: 
          ENV_NAME: ${{ inputs.environment }}
        run: write-host "Approve for $($env.ENV_NAME)"

  deploy-ui:
    # since we have an optional approval gate, shortcut the 'needs' of this job using 'always()' 
    # if the approval gate was not required for this run, then we still want to run this step if the approval gate was skipped
    # if the approval gate was required for this run, then only run this job if the approval was completed successfully
    if: ${{ always() && (needs.approval-gate.result == 'success' || needs.approval-gate.result == 'skipped') }}
    concurrency:
      cancel-in-progress: false
      group: ${{ inputs.environment }}-deploy-ui
    uses: ./.github/workflows/deploy-ui.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
    needs: 
      - approval-gate
        
  deploy-api:
    if: ${{ always() && (needs.approval-gate.result == 'success' || needs.approval-gate.result == 'skipped') }}
    concurrency:
        cancel-in-progress: false
        group: ${{ inputs.environment }}-deploy-api
    uses: ./.github/workflows/deploy-api.yml
    with:
        environment: ${{ inputs.environment }}
    secrets: inherit
    needs:
        - approval-gate

  deploy-functions:
    if: ${{ always() && (needs.approval-gate.result == 'success' || needs.approval-gate.result == 'skipped') }}
    concurrency:
        cancel-in-progress: false
        group: ${{ inputs.environment }}-deploy-function
    uses: ./.github/workflows/deploy-function.yml
    with:
        environment: ${{ inputs.environment }}
    secrets: inherit
    needs:
        - approval-gate