name: Hotfix (PP to Prod)

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  hotfix-validate:
    ##f: startsWith(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest
    steps:
      - run: |
          $branchName = $env:GITHUB_REF_NAME
          Write-host "Your branch is $($branchName)..."
          if(-not($branchName.StartsWith('hotfix/','CurrentCultureIgnoreCase'))) {
              Write-Host "Cannot start the Hotfix process - your branch must start with 'hotfix/'"
              exit 1
          }
          Write-Host "Cannot start the Hotfix process - your branch must start with 'hotfix/'"

  build:
    uses: ./.github/workflows/publish-code.yml
    secrets: inherit
    needs: hotfix-validate

  unit-test:
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit
    needs: hotfix-validate

  pp-deploy:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: pp
    secrets: inherit
    needs:
      - hotfix-validate
      - build
      - unit-test

  pr-to-main:
    runs-on: ubuntu-latest
    needs: 
      - pp-deploy
      - hotfix-validate
      - build
      - unit-test
    steps:
      - uses: actions/checkout@v3
      - name: create pull request
        run: |
          gh pr create -B $env:BASE_BRANCH -H $env:CURRENT_BRANCH `
              --title 'Hotfix Merge $($env:CURRENT_BRANCH) into $($env:BASE_BRANCH)' `
              --body 'Created by Hotfix workflow'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          BASE_BRANCH: 'main'
          CURRENT_BRANCH: ${{ github.ref_name }}
  
  prod-deploy:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: prod
    secrets: inherit
    needs:
      - pp-deploy