name: Hotfix (PP to Prod)

on:
    workflow_dispatch:

defaults:
    run:
        shell: pwsh

jobs:
    hotfix-validate:
        ##f: startsWith(github.head_ref, 'hotfix/')
        runs-on: ubuntu-latest
        env:
            BRANCH: ${{ github.head_ref }}
        steps:
            - run: |
                $branchName = $env.BRANCH;
                if(-not($branchName.StartsWith('hotfix/','CurrentCultureIgnoreCase'))) {
                    Write-Host "Your branch '$($branchName)' must start with 'hotfix/'";
                    exit 1;
                }
    
    build:
        uses: ./.github/workflows/publish-code.yml
        secrets: inherit
        needs: hotfix-validate

    unit-test:
        uses: ./.github/workflows/unit-test.yml
        secrets: inherit
        needs: hotfix-validate

    pp-deploy:
        uses: ./.github/workflows/deploy-environment.yml
        with:
            environment: pp
        secrets: inherit
        needs:
            - hotfix-validate
            - build
            - unit-test

    prod-deploy:
        uses: ./.github/workflows/deploy-environment.yml
        with:
            environment: prod
        secrets: inherit
        needs:
            - pp-deploy