name: Hotfix (PP to Prod)

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  hotfix-validate:
    runs-on: ubuntu-latest
    steps:
      - run: |
          $branchName = $env:GITHUB_REF_NAME
          Write-host "Your branch is $($branchName)..."
          if(-not($branchName.StartsWith('hotfix/','CurrentCultureIgnoreCase'))) {
              Write-Host "Cannot start the Hotfix process - your branch must start with 'hotfix/'"
              exit 1
          }
          Write-Host "Cannot start the Hotfix process - your branch must start with 'hotfix/'"

  build:
    uses: ./.github/workflows/publish-code.yml
    secrets: inherit
    needs: hotfix-validate

  unit-test:
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit
    needs: hotfix-validate

  pp-hotfix-approval-gate:
    runs-on: ubuntu-latest
    environment: "pp-approval"
    concurrency:
      cancel-in-progress: true
      group: pp-approval
    steps:
      - name: approved
        env: 
          ENV_NAME: pp
        run: write-host "Approve for $($env.ENV_NAME)"
        
  pp-deploy:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: pp
    secrets: inherit
    needs:
      - pp-hotfix-approval-gate

  prod-hotfix-approval-gate:
    runs-on: ubuntu-latest
    environment: "prod-approval"
    concurrency:
      cancel-in-progress: true
      group: prod-approval
    steps:
      - name: approved
        env: 
          ENV_NAME: prod
        run: write-host "Approve for $($env.ENV_NAME)"

  pr-to-main:
    runs-on: ubuntu-latest
    needs: 
      - prod-hotfix-approval-gate

    steps:
      - uses: actions/checkout@v3

      - name: create pull request
        run: |
          gh pr create -B $env:BASE_BRANCH -H $env:CURRENT_BRANCH `
              --title "Hotfix PR $($env:CURRENT_BRANCH) into $($env:BASE_BRANCH)" `
              --body "Created by Hotfix workflow"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: 'main'
          CURRENT_BRANCH: ${{ github.ref_name }}
  
  prod-deploy:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: prod
      requires_deployment_approval: false
    secrets: inherit
    needs:
      - prod-hotfix-approval-gate