# Workflow name
name: Build Code

# Controls when the workflow will run
on:
  # This is a reusable workflow
  workflow_call:

defaults:
  run:
    shell: pwsh

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "BUILDING THE CODE..."